#!/bin/bash

apptitle="Arch Linux Fast Install (archfi) - Version: 2022.11.21.01.44.43 (GPLv3)"
baseurl=https://raw.githubusercontent.com/MatMoul/archfi/master
cpl=0
skipfont="0"
fspkgs=""
parallelDownloads=15
kernel="linux-lts" # Set Kernel , Check official website for different kernels https://wiki.archlinux.org/title/Kernel
hostname="gan45ha" # Hostname
locale="en_US"
region="Asia"
city="Mumbai"
rootpassword="root"

pre() {
  pacman -Sy --needed dialog arch-install-scripts reflector
  reflector -l 10 --sort rate --save /etc/pacman.d/mirrorlist --verbose
  sed -i "s/.*ParallelDownloads.*/ParallelDownloads = ${parallelDownloads}/" /etc/pacman.conf

}

mainmenu() {
  if [ "${1}" = "" ]; then
    nextitem="."
  else
    nextitem=${1}
  fi
  options=()
  options+=("${txtdiskpartmenu}" "")
  options+=("${txtselectpartsmenu}" "")
  options+=("" "")
  options+=("${txtreboot}" "")
  sel=$(dialog --backtitle "${apptitle}" --title "${txtmainmenu}" --cancel-button "${txtexit}" --default-item "${nextitem}" --menu "" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ "$?" = "0" ]; then
    case ${sel} in
    "${txtdiskpartmenu}")
      diskpartmenu
      nextitem="${txtselectpartsmenu}"
      ;;
    "${txtselectpartsmenu}")
      selectparts
      nextitem="${txtreboot}"
      ;;
    "${txtreboot}")
      rebootpc
      nextitem="${txtreboot}"
      ;;
    esac
    mainmenu "${nextitem}"
  else
    clear
  fi
}

# --------------------------------------------------------
diskpartmenu() {
  diskpartcfdisk
  nextitem="${txteditparts} (cfdisk)"
}

diskpartcfdisk() {
  device=$(selectdisk "${txteditparts} (cfdisk)")
  if [ "$?" = "0" ]; then
    clear
    cfdisk ${device}
  fi
}

selectdisk() {
  items=$(lsblk -d -p -n -l -o NAME,SIZE -e 7,11)
  options=()
  IFS_ORIG=$IFS
  IFS=$'\n'
  for item in ${items}; do
    options+=("${item}" "")
  done
  IFS=$IFS_ORIG
  result=$(dialog --backtitle "${APPTITLE}" --title "${1}" --menu "" 0 0 0 "${options[@]}" 3>&1 1>&2 2>&3)
  if [ "$?" != "0" ]; then
    return 1
  fi
  echo ${result%%\ *}
  return 0
}

# --------------------------------------------------------
# Select Disk for Partitions
selectparts() {
  items=$(lsblk -p -n -l -o NAME -e 7,11)
  options=()
  for item in ${items}; do
    options+=("${item}" "")
  done

  bootdev=$(dialog --backtitle "${apptitle}" --title "${txtselectpartsmenu}" --default-item "${bootdev}" --menu "${txtselectdevice//%1/boot}" 0 0 0 \
    "none" "-" \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ ! "$?" = "0" ]; then
    return 1
  else
    if [ "${bootdev}" = "none" ]; then
      bootdev=
    fi
  fi

  swapdev=$(dialog --backtitle "${apptitle}" --title "${txtselectpartsmenu}" --default-item "${swapdev}" --menu "${txtselectdevice//%1/swap}" 0 0 0 \
    "none" "-" \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ ! "$?" = "0" ]; then
    return 1
  else
    if [ "${swapdev}" = "none" ]; then
      swapdev=
    fi
  fi

  rootdev=$(dialog --backtitle "${apptitle}" --title "${txtselectpartsmenu}" --default-item "${rootdev}" --menu "${txtselectdevice//%1/root}" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ ! "$?" = "0" ]; then
    return 1
  fi
  realrootdev=${rootdev}

  homedev=$(dialog --backtitle "${apptitle}" --title "${txtselectpartsmenu}" --menu "${txtselectdevice//%1/home}" 0 0 0 \
    "none" "-" \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ ! "$?" = "0" ]; then
    return 1
  else
    if [ "${homedev}" = "none" ]; then
      homedev=
    fi
  fi

  msg="${txtselecteddevices}\n\n"
  msg=${msg}"boot : "${bootdev}"\n"
  msg=${msg}"swap : "${swapdev}"\n"
  msg=${msg}"root : "${rootdev}"\n"
  msg=${msg}"home : "${homedev}"\n\n"
  if (dialog --backtitle "${apptitle}" --title "${txtselectpartsmenu}" --yesno "${msg}" 0 0); then
    isnvme=0
    if [ "${bootdev::8}" == "/dev/nvm" ]; then
      isnvme=1
    fi
    if [ "${rootdev::8}" == "/dev/nvm" ]; then
      isnvme=1
    fi
    mountmenu
  fi
}
# --------------------------------------------------------

# --------------------------------------------------------
mountmenu() {
  if [ "${1}" = "" ]; then
    nextitem="."
  else
    nextitem=${1}
  fi
  options=()
  options+=("${txtformatdevices}" "")
  options+=("${txtmount}" "${txtmountdesc}")
  sel=$(dialog --backtitle "${apptitle}" --title "${txtformatmountmenu}" --cancel-button "${txtback}" --default-item "${nextitem}" --menu "" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ "$?" = "0" ]; then
    case ${sel} in
    "${txtformatdevices}")
      formatdevices
      nextitem="${txtmount}"
      ;;
    "${txtmount}")
      mountparts
      nextitem="${txtmount}"
      ;;
    esac
    mountmenu "${nextitem}"
  fi
}

formatdevices() {
  if (dialog --backtitle "${apptitle}" --title "${txtformatdevices}" --defaultno --yesno "${txtformatdeviceconfirm}" 0 0); then
    fspkgs=""
    if [ ! "${bootdev}" = "" ]; then
      formatbootdevice boot ${bootdev}
    fi
    if [ ! "${swapdev}" = "" ]; then
      formatswapdevice swap ${swapdev}
    fi
    formatdevice root ${rootdev}
    if [ ! "${homedev}" = "" ]; then
      formatdevice home ${homedev}
    fi
  fi
}
formatbootdevice() {
  options=()
  if [ "${efimode}" == "1" ] || [ "${efimode}" = "2" ]; then
    options+=("fat32" "(EFI)")
  fi
  options+=("ext2" "")
  options+=("ext3" "")
  options+=("ext4" "")
  if [ ! "${efimode}" = "1" ] && [ ! "${efimode}" = "2" ]; then
    options+=("fat32" "(EFI)")
  fi
  sel=$(dialog --backtitle "${apptitle}" --title "${txtformatdevice}" --menu "${txtselectpartformat//%1/${1} (${2})}" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ ! "$?" = "0" ]; then
    return 1
  fi
  clear
  echo "${txtformatingpart//%1/${2}} ${sel}"
  echo "----------------------------------------------"
  case ${sel} in
  ext2)
    echo "mkfs.ext2 ${2}"
    mkfs.ext2 ${2}
    ;;
  ext3)
    echo "mkfs.ext3 ${2}"
    mkfs.ext3 ${2}
    ;;
  ext4)
    echo "mkfs.ext4 ${2}"
    mkfs.ext4 ${2}
    ;;
  fat32)
    fspkgs="${fspkgs[@]} dosfstools"
    echo "mkfs.fat ${2}"
    mkfs.fat ${2}
    ;;
  esac
  echo ""
  pressanykey
}
formatswapdevice() {
  options=()
  options+=("swap" "")
  sel=$(dialog --backtitle "${apptitle}" --title "${txtformatdevice}" --menu "${txtselectpartformat//%1/${1} (${2})}" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ ! "$?" = "0" ]; then
    return 1
  fi
  clear
  echo "${txtformatingpart//%1/${swapdev}} swap"
  echo "----------------------------------------------------"
  case ${sel} in
  swap)
    echo "mkswap ${swapdev}"
    mkswap ${swapdev}
    echo ""
    pressanykey
    ;;
  esac
  clear
}
formatdevice() {
  options=()
  options+=("btrfs" "")
  options+=("ext4" "")
  options+=("ext3" "")
  options+=("ext2" "")
  options+=("xfs" "")
  options+=("f2fs" "")
  options+=("jfs" "")
  options+=("reiserfs" "")
  if [ ! "${3}" = "noluks" ]; then
    options+=("luks" "encrypted")
  fi
  sel=$(dialog --backtitle "${apptitle}" --title "${txtformatdevice}" --menu "${txtselectpartformat//%1/${1} (${2})}" 0 0 0 \
    "${options[@]}" \
    3>&1 1>&2 2>&3)
  if [ ! "$?" = "0" ]; then
    return 1
  fi
  clear
  echo "${txtformatingpart//%1/${2}} ${sel}"
  echo "----------------------------------------------"
  case ${sel} in
  btrfs)
    fspkgs="${fspkgs[@]} btrfs-progs"
    echo "mkfs.btrfs -f ${2}"
    mkfs.btrfs -f ${2}
    if [ "${1}" = "root" ]; then
      echo "mount ${2} /mnt"
      echo "btrfs subvolume create /mnt/root"
      echo "btrfs subvolume set-default /mnt/root"
      echo "umount /mnt"
      mount ${2} /mnt
      btrfs subvolume create /mnt/root
      btrfs subvolume set-default /mnt/root
      umount /mnt
    fi
    ;;
  ext4)
    echo "mkfs.ext4 ${2}"
    mkfs.ext4 ${2}
    ;;
  ext3)
    echo "mkfs.ext3 ${2}"
    mkfs.ext3 ${2}
    ;;
  ext2)
    echo "mkfs.ext2 ${2}"
    mkfs.ext2 ${2}
    ;;
  xfs)
    fspkgs="${fspkgs[@]} xfsprogs"
    echo "mkfs.xfs -f ${2}"
    mkfs.xfs -f ${2}
    ;;
  f2fs)
    fspkgs="${fspkgs[@]} f2fs-tools"
    echo "mkfs.f2fs -f $2"
    mkfs.f2fs -f $2
    ;;
  jfs)
    fspkgs="${fspkgs[@]} jfsutils"
    echo "mkfs.jfs -f ${2}"
    mkfs.jfs -f ${2}
    ;;
  reiserfs)
    fspkgs="${fspkgs[@]} reiserfsprogs"
    echo "mkfs.reiserfs -f ${2}"
    mkfs.reiserfs -f ${2}
    ;;
  luks)
    echo "${txtcreateluksdevice}"
    echo "cryptsetup luksFormat ${2}"
    cryptsetup luksFormat ${2}
    if [ ! "$?" = "0" ]; then
      pressanykey
      return 1
    fi
    pressanykey
    echo ""
    echo "${txtopenluksdevice}"
    echo "cryptsetup luksOpen ${2} ${1}"
    cryptsetup luksOpen ${2} ${1}
    if [ ! "$?" = "0" ]; then
      pressanykey
      return 1
    fi
    pressanykey
    options=()
    options+=("normal" "")
    options+=("fast" "")
    sel=$(dialog --backtitle "${apptitle}" --title "${txtformatdevice}" --menu "Wipe device ?" --cancel-button="${txtignore}" 0 0 0 \
      "${options[@]}" \
      3>&1 1>&2 2>&3)
    if [ "$?" = "0" ]; then
      case ${sel} in
      normal)
        echo "dd if=/dev/zero of=/dev/mapper/${1}"
        dd if=/dev/zero of=/dev/mapper/${1} &
        PID=$! &>/dev/null
        ;;
      fast)
        echo "dd if=/dev/zero of=/dev/mapper/${1} bs=60M"
        dd if=/dev/zero of=/dev/mapper/${1} bs=60M &
        PID=$! &>/dev/null
        ;;
      esac
      clear
      sleep 1
      while kill -USR1 ${PID} &>/dev/null; do
        sleep 1
      done
    fi
    echo ""
    pressanykey
    formatdevice ${1} /dev/mapper/${1} noluks
    if [ "${1}" = "root" ]; then
      realrootdev=${rootdev}
      rootdev=/dev/mapper/${1}
      luksroot=1
      luksrootuuid=$(cryptsetup luksUUID ${2})
    else
      case ${1} in
      home) homedev=/dev/mapper/${1} ;;
      esac
      luksdrive=1
      crypttab="\n${1}    UUID=$(cryptsetup luksUUID ${2})    none"
    fi
    echo ""
    echo "${txtluksdevicecreated}"
    ;;
  esac
  echo ""
  pressanykey
}

mountparts() {
  clear
  echo "mount ${rootdev} /mnt"
  mount ${rootdev} /mnt
  echo "mkdir /mnt/{boot,home}"
  mkdir /mnt/{boot,home} 2>/dev/null
  if [ ! "${bootdev}" = "" ]; then
    echo "mount ${bootdev} /mnt/boot"
    mount ${bootdev} /mnt/boot
  fi
  if [ ! "${swapdev}" = "" ]; then
    echo "swapon ${swapdev}"
    swapon ${swapdev}
  fi
  if [ ! "${homedev}" = "" ]; then
    echo "mount ${homedev} /mnt/home"
    mount ${homedev} /mnt/home
  fi
  pressanykey
  post
  # installmenu
}
# --------------------------------------------------------

pressanykey() {
  read -n1 -p "${txtpressanykey}"
}

# --------------------------------------------------------
installmenu() {
  # if [ "${1}" = "" ]; then
  #   nextitem="${txtinstallarchlinux}"
  # else
  #   nextitem=${1}
  # fi
}

archsetkeymap() {
  keymap="us"
  echo "echo \"KEYMAP=${keymap}\" > /mnt/etc/vconsole.conf"
  # echo "KEYMAP=${keymap}" > /mnt/etc/vconsole.conf
}

loadstrings() {

  locale=en_US.UTF-8
  #font=

  txtexit="Exit"
  txtback="Back"
  txtignore="Ignore"

  txtselectserver="Select source server :"

  txtmainmenu="Main Menu"
  txtlanguage="Language"
  txtsetkeymap="Set Keyboard Layout"
  txteditor="Editor"
  txtdiskpartmenu="Disk Partitions"
  txtselectpartsmenu="Select Partitions and Install"
  txthelp="Help"
  txtchangelog="Changelog"
  txtreboot="Reboot"

  txtautoparts="Auto Partitions"
  txteditparts="Edit Partitions"

  txtautopartsconfirm="Selected device : %1\n\nAll data will be erased ! \n\nContinue ?"

  txtautopartclear="Clear all partition data"
  txtautopartcreate="Create %1 partition"
  txthybridpartcreate="Set hybrid MBR"
  txtautopartsettype="Set %1 partition type"

  txtselectdevice="Select %1 device :"
  txtselecteddevices="Selected devices :"

  txtformatmountmenu="Format and Mount"
  txtformatdevices="Format Devices"
  txtformatdevice="Format Device"
  txtmount="Mount"
  txtunmount="Unmount"
  txtmountdesc="Install or Config"

  txtformatdeviceconfirm="Warning, all data on selected devices will be erased ! \nFormat devices ?"

  txtselectpartformat="Select partition format for %1 :"
  txtformatingpart="Formatting partition %1 as"
  txtcreateluksdevice="Create luks device :"
  txtopenluksdevice="Open luks device :"
  txtluksdevicecreated="luks device created !"

  txtinstallmenu="Install Menu"

  txtarchinstallmenu="Arch Install Menu"

  txtselectmirrorsbycountry="Select mirrors by country"
  txtselectcountry="Select country"
  txteditmirrorlist="Edit mirrorlist"
  txtfiltermirrorlist="Filter mirrorlist"
  txtparalleldownloads="Parallel Downloads"
  txtinstallarchlinux="Install Arch Linux"
  txtinstallarchlinuxkernel="Kernel"
  txtinstallarchlinuxfirmwares="Firmwares"
  txtinstallarchlinuxfilesystems="File Systems"
  txtinstallarchlinuxcustompackagelist="Custom Package List"
  txtconfigarchlinux="Config Arch Linux"

  txtparallelprompt="Number of packages to download in Parallel"
  txtincorrectinput="Please enter a number greater than 0"

  txtsethostname="Set Computer Name"
  txtsetfont="Set Font"
  txtsetlocale="Set Locale"
  txtsettime="Set Time"
  txtsetrootpassword="Set root password"

  txthwclock="Hardware clock :"
  txthwclockutc="UTC"
  txthwclocklocal="Local"

  txtbootloader="Bootloader"
  txtbootloadermenu="Choose your bootloader"

  txtefibootmgr="efibootmgr is required for EFI computers."

  txtbootloadergrubmenu="Grub Install Menu"
  txtrungrubmakeconfig="Run grub-mkconfig ?"
  txtgrubluksdetected="Encrypted root partion !\n\nAdd cryptdevice= to GRUB_CMDLINE_LINUX in /etc/default/grub ?"

  txtbootloadersyslinuxmenu="Syslinux Install Menu"
  txtsyslinuxaddefibootmgr="EFI install require efibootmgr"
  txtsyslinuxaddgptfdisk="GPT disk require gptfdisk"
  txtsyslinuxaddmtools="FAT boot part require mtools"

  txtbootloadersystemdmenu="Systemd-boot Install Menu"

  txtbootloaderrefindmenu="rEFInd Install Menu"

  txtextrasmenu="Extras"

  txtoptional="Optional"
  txtrecommandeasyinst="Recommanded for easy install"
  txtset="Set %1"
  txtgenerate="Generate %1"
  txtedit="Edit %1"
  txtinstall="Install %1"
  txtenable="Enable %1"

  txtpressanykey="Press any key to continue."

  txtarchdidesc="Full desktop install script"
  txtinstallarchdi="Arch Linux Desktop Install (archdi) is a second script who can help you to install a full workstation.\n\nYou can just launch the script or install it. Choose in the next menu."
  txtarchdiinstallandlaunch="Install and run archdi"
  txtarchdiinstall="Install archdi"
  txtarchdilaunch="Launch archdi"
}

post() {
  echo "Installing Arch..."
  pacstrap /mnt base ${kernel} ${kernel}-firmware
  genfstab -U /mnt >>/mnt/etc/fstab

  arch-chroot /mnt
  echo "Configuring Arch..."
  echo "${hostname}" >/mnt/etc/hostname
  echo "KEYMAP=${keymap}" >/mnt/etc/vconsole.conf
  ln -sf /usr/share/zoneinfo/${region}/${city} /etc/localtime
  mkinitcpio -P
  passwd ${rootpassword}
  grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB --recheck
  grub-mkconfig -o /boot/grub/grub.cfg
}

# echo "Init pacman, please wait..."
# systemctl start pacman-init.service
# pacman -Sy --needed arch-install-scripts dialog
dmesg | grep efi: >/dev/null
if [ "$?" == "1" ]; then
  if [ "${eficomputer}" != "1" ]; then
    eficomputer=0
  fi
else
  eficomputer=1
  if [ "${efimode}" == "" ]; then
    efimode=1
  fi
fi
cat <<EOF >dialog.archfi
use_shadow = OFF
title_color = (BLACK,WHITE,OFF)
button_label_active_color = (WHITE,BLUE,ON)
button_label_inactive_color = (BLACK,WHITE,OFF)
tag_color = (BLACK,WHITE,OFF)
tag_selected_color = (WHITE,BLUE,ON)
tag_key_color = (BLACK,WHITE,OFF)
tag_key_selected_color = (WHITE,BLUE,ON)
check_color = tag_color
check_selected_color = tag_selected_color
EOF
export DIALOGRC="dialog.archfi"
loadstrings
EDITOR=vim
pre
mainmenu
rm dialog.archfi

exit 0
